export const ENTRIES_REQUESTED = "ENTRIES_REQUESTED";
export const ENTRIES_SUCCEEDED = "ENTRIES_SUCCEEDED";
export const ENTRIES_FAILED = "ENTRIES_FAILED";
export const CLEAN_STATE = 'CLEAN_STATE';
