version: "3"
services:
  app:
    build: .
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/opt/app
      - sdsnodemodules:/opt/app/node_modules/
    entrypoint:
      - /bin/sh
      - -c
      - |
        npm run start
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: 192.168.0.8
volumes:
  sdsnodemodules: