version: "3"
services:
  app:
    image: substance-demo-sn
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/opt/app
      - subs-demo-sn-nodemodules:/opt/app/node_modules/
    command: sh -c "expo start"
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: 192.168.0.8
volumes:
  subs-demo-sn-nodemodules: